### ISSUE TITLE
`openInput` return value is unstable

### ISSUE THREAD

**Issue by bgrange** [ninegua/PortMidi#15]
In the first screenshot, we see that opening an device won't work unless the call to openInput is prefaced by a call to getDeviceInfo. Very strange indeed...

<img width="731" alt="screen shot 2018-07-28 at 11 42 08 am" src="https://user-images.githubusercontent.com/1594015/43355378-8042f22c-925b-11e8-863c-5919fd1854b0.png">

In this second one, we see that calling isLeft on a device will cause it to switch! (but only the first time. It settles into an equilibrium of error.)
<img width="718" alt="screen shot 2018-07-28 at 11 41 17 am" src="https://user-images.githubusercontent.com/1594015/43355380-827338a4-925b-11e8-8e9d-97afbad56fbf.png">

Also, I'd like to politely point out that the Left value in an Either should be the erroneous value, and the Right should be the valid one. That is, if one hopes to use Either as a monad.

Thank you,
Ben

**Comment by OlivierSohn** [comment]
Hi @bgrange, I quickly looked at the C code, and I suspect a missing call (on your side) to `PortMidi.initialize`, can you please double check?

> Also, I'd like to politely point out that the Left value in an Either should be the erroneous value, and the Right should be the valid one. That is, if one hopes to use Either as a monad.

Absolutely, and the Either conventions for returning errors are changed in `master` but not pushed to hackage yet.

**Comment by OlivierSohn** [comment]
@bgrange did the suggested fix work for you? It seems to me that that's the problem so I'll close the issue. Feel free to reopen if you think otherwise.

**Comment by bgrange** [comment]
Problem's still there
<img width="506" alt="screen shot 2018-07-28 at 2 56 53 pm" src="https://user-images.githubusercontent.com/1594015/43356796-e39a605a-9277-11e8-9c3f-0559acfb1dbd.png">
<img width="488" alt="screen shot 2018-07-28 at 2 49 46 pm" src="https://user-images.githubusercontent.com/1594015/43356798-e547ac82-9277-11e8-81b0-04ed8523e93e.png">

**Comment by OlivierSohn** [comment]
Oh, I see.

The problem here is that the second time, you're trying to open a stream that's already opened : it errors, and it's normal. I think for it to work you'd need to first close the stream using the `close` function.

**Comment by bgrange** [comment]
Thanks.

**Comment by OlivierSohn** [comment]
Btw, the new version is on Hackage now, with Either conventions fixed (since you were mentionning this issue at the beginning!).
