### ISSUE TITLE
Pushing a new version to hackage

### ISSUE THREAD

**Issue by OlivierSohn** [ninegua/PortMidi#16]
I'd like to see the latest master changes on hackage, I can push the package if needed, but would need to be added to the corresponding hackage maintainer group (to do this, first go here : http://hackage.haskell.org/package/PortMidi/maintain and then click "Maintainer group" and then "Edit").

Thanks!

**Comment by ninegua** [comment]
Just uploaded a candidate: https://hackage.haskell.org/package/PortMidi-0.2.0.0/candidate

Please see if it looks ok.

**Comment by ninegua** [comment]
Added you as a Hackage maintainer too.

**Comment by OlivierSohn** [comment]
It looks good, I guess the doc will be available once built by hackage.

Thanks for adding me as a maintainer!

**Comment by OlivierSohn** [comment]
If you agree I will validate the module tomorrow to switch it from candidate to official.

**Comment by ninegua** [comment]
Sounds good. Thanks!

**Comment by OlivierSohn** [comment]
It's published! (I think I read somewhere that we should wait up-to 30 minutes before it's visible)
