### ISSUE TITLE
Fix support for older GHCs + add CI script

### ISSUE THREAD

**Issue by OlivierSohn** [ninegua/PortMidi#17]
My modifications introduced [regressions on older GHCs (<= 7.8)](https://matrix.hackage.haskell.org/package/PortMidi#GHC-7.8/PortMidi-0.2.0.0)

I'll try to fix this when I have time.

Also I'd like to introduce a CI script on this github repository to be able to automatically detect those regressions early-on, instead of relying on hackage build matrix for CI :)

**Comment by OlivierSohn** [comment]
@ninegua would it be possible for you (since you're repo owner, I think I can't do that myself) to associate the repo with Travis CI (https://travis-ci.org/) ? it is quite simple, and it would allow me then to push the CI script! Then, every time a commit is made to the repo, travis builds it, so it's easy to catch regressions this way... Thanks!

**Comment by ninegua** [comment]
Sorry, I can't sign up Travis CI because it demands access to everything. But if you already have a Travis account, I can help hook it up to this repo.

**Comment by OlivierSohn** [comment]
Ok, my account is https://travis-ci.org/OlivierSohn

**Comment by ninegua** [comment]
Thanks for stepping up. It's telling me that I need three things: User, Token, and Domain. You may also email me if the token is supposed to be kept secret.

**Comment by OlivierSohn** [comment]
Hmm, yeah it feels strange that I need to send you my private token. But if you are setting up a [github organization](https://help.github.com/articles/about-organizations/), I guess you could make me an admin of it, and then I could setup Travis / enter my user token, etc... would that be ok for you?

**Comment by ninegua** [comment]
Thanks for the suggestion, it is an interesting workaround. I've created an organization and moved the repo over.

**Comment by ninegua** [comment]
@OlivierSohn Sorry for the delay, but I've just made you the admin/owner of the PortMidi organization, so you should be able to add CI to this repo.

**Comment by OlivierSohn** [comment]
@ninegua Thanks, no problem, I was busy doing other stuff these days :) hopefully I'll find time to do this soon!

**Comment by OlivierSohn** [comment]
While doing the work in #18 I found that supporting older GHCs may be nonsensical after all, and reading [this article](https://www.snoyman.com/blog/2018/07/stop-supporting-older-ghcs) confirmed my intuition:

> A generally accepted rule of thumb is three major GHC releases. At the time of writing, that would mean supporting GHC 8.0, 8.2, and 8.4. I recommend only supporting the latest minor version of each line, which would mean GHC 8.0.2, 8.2.2, and 8.4.3.

**Comment by ninegua** [comment]
The error looks like related to stack on MacOS?

In any case, dropping it from CI doesn't mean that PortMidi no longer runs on older GHC, just that we do not test it on older GHC. I think it is fine to do this.

**Comment by OlivierSohn** [comment]
There are 2 errors I mentionned, one is stack-related (in the CI script), but others (the ones I was attempting to fix while opening this issue, and then thought it would be overkill) are Haskell-related (they are not visible on hackage anymore because I changed the bounds of base for the latest release, on hackage directly and a build has been done in-between).

**Comment by OlivierSohn** [comment]
I'm closing this issue as it is not relevant anymore.
