### ISSUE TITLE
Erroneous Incoming System Exclusives

### ISSUE THREAD

**Issue by REBradley** [ninegua/PortMidi#20]
Greetings. First of all, I'd really appreciate any help with this issue. I'm ready to do what I can to help.

I'm deserializing inbound sysex from a vintage Yamaha hardware synthesizer, and PortMidi is not giving me the correct stream of inbound bytes. I know what to expect, given the request I've made to the synth. I also have a utility program, PocketMidi (on Mac) that gives the correct bytes. I am 100% sure of a bug, 60% sure it's in the coremidi integration.

I repeatedly poll PMStream until I get a GotData.
I read the PMEvents.
From each PMEvent, I'm taking the message (::CLong), and extracting the first 4 bytes because I read that there are no more than 4 bytes of actual data in each message.

```
toBytes :: CLong -> [Word8]
toBytes bit64 = map (fromIntegral . f) [0,8..24] --PM:24 not 56; 4 bytes not 8
  where
    f = \position -> shiftR bit64 position .&. 0xFF
```

Very simple. BUT what I get back does not look as it should. I took a picture.

![portmidierr](https://user-images.githubusercontent.com/6488352/142303942-be9350aa-408f-41bb-b111-5929733d8820.JPG)

Profile gives me the reported bytes sent according to the synth, and the computed number of bytes gotten by taking the length of the packet. 

The list within the Profile gives the me timestamped chunks of 4 bytes. Below that, on the command line, I typed what I was expecting. 

The second chunk gives me two erroneous trailing zeros, among other issues.
Here's the whole thing typed without timestamps...

Given:  F0 43 75 00   00 02 00 00  11 01 20 20   20 6D 6F 6E   6F 20 20 6D   20 38 01 20   64 00 32 02
Got   :  F0 43 75 00    00 02 11  01   20 20 20 6D   6F 6E 6F 20  38 01 64 00   32 02 00 00

Otherwise, I really like this library. It's fast, and the interface is simple and appropriate.

What do we need to do in order to fix this? It's unlikely that any of you have (or want) my synth, but this problem should be easy to reproduce with any syx-dumping machine.

**Comment by OlivierSohn** [comment]
Hello REBradley,

To gain insight as to what might be wrong I would suggest the printf debugging approach to see where the data gets "corrupted". For example you could add logs in the c code (write to a file for example).

Olivier

**Comment by REBradley** [comment]
Ok I will do that.

**Comment by REBradley** [comment]
Resolved.
