### ISSUE TITLE
Reading events (performance optimization)

### ISSUE THREAD

**Issue by OlivierSohn** [ninegua/PortMidi#6]
Today, each call of `readEvents` dynamically allocates and deallocates a fixed-size pinned array using `allocaArray`, containing 256 `PMEvent`s.

Considering that `readEvents` is the only exported function allowing to poll / read messages, if a user needs to receive messages at a low latency (say 1 millisecond) then, every millisecond, this function will be called, and even if there is nothing to read, every call will allocate / dallocate, thereby potentially increasing overall memory fragmentation, and maybe also block for some time.

I think we can improve this situation in 2 ways:
- provide a binding to `Pm_Poll` so that we can first check if there is data before calling the `readEvents` call.
- provide a `readEventsToBuffer` that takes an already allocated buffer + its size, and returns an `Int` saying how many messages were written to it.

What do you think?

Implementation suggestions are welcome, and since I need this in my application I'll probably take a shot at it.

**Comment by ninegua** [comment]
Both sound plausible, would appreciate a PR. Thanks!
