### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by OlivierSohn** [ninegua/PortMidi#9]
on hackage there seems to be a changelog: https://hackage.haskell.org/package/PortMidi-0.1.6.1/changelog

As part of #8  I wanted to add a comment in the changelog but couldn't find it. What should I do? Should I create a CHANGELOG file at the root and copy paste what I found on hackage in it?

**Comment by ninegua** [comment]
The changelog was just the text from `git log` (or `darcs log`) manually produced before I push a new version to hackage. So I didn't include this file in the repo. Any suggestion on the best practice here?

**Comment by OlivierSohn** [comment]
Ok, the best practice would be to put this file under source control, and about the content,  I think a changelog should be more concise than the list of commits : I personally like this approach https://keepachangelog.com/en/1.0.0/
